name: Deployment-dev

on:
  push:
    branches:
      - main

jobs:
  deployment-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: deploy
        run: |
          echo ${{ vars.INFRA }}