name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: deploy
        run: |
          echo ${{ vars.INFRA }}