name: Deployment-prod
on:
  # push:
  #   branches:
  #     - dev
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  CHK_TAG:  
    runs-on: ubuntu-latest
    outputs:
      PART: ${{ steps.get-tag.outputs.part }}
      TAG: ${{ steps.get-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Assign or Get TAG
        id: get-tag
        uses: delta-bravo277/github-action-tag@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none

  deployment-prod:
    # if: github.event.pull_request.merged == true
    needs: CHK_TAG
    if: ${{ needs.CHK_TAG.outputs.PART != 'none' }}
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - env:
          TAG: ${{ needs.CHK_TAG.outputs.TAG }}
        name: deploy  
        run: |
          echo ${{ vars.INFRA }}
          echo ${{ env.TAG }}
