name: Deployment-prod

on:
  push:
    branches:
      - main

jobs:
  deployment-prod:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: deploy
        run: |
          echo ${{ vars.INFRA }}